dist: precise
language: java
matrix:
  include:
    - jdk: oraclejdk8
    - addons:
        apt:
          packages:
            - openjdk-7-jdk
      jdk: openjdk7
    - addons:
        apt:
          packages:
            - oracle-java7-installer
      jdk: oraclejdk7
    - addons:
        apt:
          packages:
            - openjdk-6-jdk
      jdk: openjdk6
before_script: unset GEM_PATH GEM_HOME JRUBY_OPTS
before_install:
  - sudo hostname "$(hostname | cut -c1-63)"
  - (cat /etc/hosts ; echo 127.0.0.1 $(hostname)) | sudo tee /etc/hosts
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz
install: ./gradlew -S -Pskip.signing assemble
script: ./gradlew -S -Pskip.signing check && bash test-asciidoctor-upstream.sh
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#asciidoctor"
