name: Build Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  test-asciidoctor-upstream:
    name: Test Asciidoctor Upstream
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os:
          - ubuntu-latest
        java:
          - '11'
        maven:
          - '3.9.1'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Java
        uses: s4u/setup-maven-action@v1.7.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
      - name: Maven version
        run: mvn -version
      - name: Upstream Build
        run: |
          unset GEM_PATH GEM_HOME JRUBY_OPTS
          ./ci/test-asciidoctor-upstream.sh
      - name: Upload reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: asciidoctorj-core-reports
          path: asciidoctorj-core/build/reports/*
      - name: Upload local gem
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: asciidoctor-gem
          path: ~/.m2/repository/rubygems/asciidoctor/**
